In [ ]:
import pandas as pd
df= pd.read_csv('/content/news_articles.csv')

In [ ]:
df.head()

author                      published  \
0     Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1  reasoning with facts  2016-10-29T08:47:11.259+03:00   
2     Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                Fed Up  2016-11-01T05:22:00.000+02:00   
4                Fed Up  2016-11-01T21:56:00.000+02:00   

                                               title  \
0  muslims busted they stole millions in govt ben...   
1  re why did attorney general loretta lynch plea...   
2  breaking weiner cooperating with fbi on hillar...   
3  pin drop speech by father of daughter kidnappe...   
4  fantastic trumps  point plan to reform healthc...   

                                                text language  \
0  print they should pay all the back all the mon...  english   
1  why did attorney general loretta lynch plead t...  english   
2  red state  \nfox news sunday reported this mor...  english   
3  email kayla mueller was a prisoner and torture...  english   
4  email healthcare reform to make america great ...  english   

              site_url                                       main_img_url  \
0  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
1  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
2  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
3  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
4  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   

   type label                            title_without_stopwords  \
0  bias  Real        muslims busted stole millions govt benefits   
1  bias  Real         attorney general loretta lynch plead fifth   
2  bias  Real  breaking weiner cooperating fbi hillary email ...   
3  bias  Real  pin drop speech father daughter kidnapped kill...   
4  bias  Real  fantastic trumps point plan reform healthcare ...   

                              text_without_stopwords  hasImage  
0  print pay back money plus interest entire fami...         1  
1  attorney general loretta lynch plead fifth bar...         1  
2  red state fox news sunday reported morning ant...         1  
3  email kayla mueller prisoner tortured isis cha...         1  
4  email healthcare reform make america great sin...         1

In [ ]:
df=df.dropna()

In [ ]:
# X contains features/independent variables
x = df[['author', 'title', 'text']]

# y contains the target/dependent variable
y = df['label']


In [ ]:
x.head()

author                                              title  \
0     Barracuda Brigade  muslims busted they stole millions in govt ben...   
1  reasoning with facts  re why did attorney general loretta lynch plea...   
2     Barracuda Brigade  breaking weiner cooperating with fbi on hillar...   
3                Fed Up  pin drop speech by father of daughter kidnappe...   
4                Fed Up  fantastic trumps  point plan to reform healthc...   

                                                text  
0  print they should pay all the back all the mon...  
1  why did attorney general loretta lynch plead t...  
2  red state  \nfox news sunday reported this mor...  
3  email kayla mueller was a prisoner and torture...  
4  email healthcare reform to make america great ...

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y = le.fit_transform(df['label'])



In [ ]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

#

# Onehot Representation

In [ ]:
message=x.copy()

In [ ]:
message.title[1]

're why did attorney general loretta lynch plead the fifth'

In [ ]:
message.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# DATA PREPROCESSING


In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [ ]:
corpus

['muslim bust stole million govt benefit',
 'attorney gener loretta lynch plead fifth',
 'break weiner cooper fbi hillari email investig',
 'pin drop speech father daughter kidnap kill isi vote donald j trump percentfedupcom',
 'fantast trump point plan reform healthcar begin bombshel percentfedupcom',
 'hillari goe absolut berserk protest ralli video',
 'break nypd readi make arrest weiner casehillari visit pedophil island least timesmoney launder underag sex payforplayproof inappropri handl classifi inform percentfedupcom',
 'wow whistleblow tell chill stori massiv voter fraud trump campaign readi lawsuit fl sec elect critic district video percentfedupcom',
 'break clinton clearedwa coordin last minut trick energ hillari base percentfedupcom',
 'evil hillari support yell fck trumpburn truck daddi fish yr son trump bumperstick video percentfedupcom',
 'yike hillari goe railspul howard dean video',
 'say goodby hollywood celeb threaten leav uslet hold percentfedupcom',
 'kid colleg giv

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2456, 3732, 1858, 2089, 4792, 4434],
 [1758, 3329, 2986, 4275, 1390, 375],
 [1464, 3092, 3516, 3666, 969, 948, 98],
 [1823, 4197, 1612, 2512, 3498, 2176, 2265, 2688, 1651, 464, 353, 2652, 2492],
 [3310, 2652, 3575, 57, 1844, 364, 765, 3406, 2492],
 [969, 3287, 832, 2722, 3565, 3928, 86],
 [1464,
  2813,
  609,
  2306,
  473,
  3092,
  1461,
  2345,
  2103,
  2332,
  4989,
  1227,
  4832,
  3149,
  2782,
  2541,
  364,
  84,
  3505,
  3393,
  2492],
 [1120,
  2226,
  1017,
  1846,
  4797,
  1744,
  2845,
  3399,
  2652,
  597,
  609,
  4203,
  3160,
  723,
  700,
  4531,
  1841,
  86,
  2492],
 [1464, 3009, 978, 4717, 468, 2639, 1965, 3841, 969, 3208, 2492],
 [2432,
  969,
  3574,
  1273,
  978,
  4906,
  4207,
  1841,
  952,
  264,
  328,
  2652,
  3300,
  86,
  2492],
 [2314, 969, 3287, 1593, 1566, 3863, 86],
 [3823, 3181, 4992, 2397, 922, 3573, 4767, 4491, 2492],
 [758, 3691, 714, 2700, 4734, 3900, 1241, 2652, 3124, 2700, 1403, 2528],
 [3495, 3334, 4087, 2652, 222, 4876, 2084, 2618

# Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2089 4792 4434]
 [   0    0    0 ... 4275 1390  375]
 [   0    0    0 ...  969  948   98]
 ...
 [   0    0    0 ... 2478 1132 1559]
 [   0    0    0 ...   98  969 3009]
 [   0    0    0 ... 3666  948 4519]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0, 2456, 3732, 1858, 2089, 4792, 4434], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((1444, 20), (1444,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
print(X_train.dtype)
print(type(X_train[0]))


int32
<class 'numpy.ndarray'>


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9866 - loss: 0.0438 - val_accuracy: 0.7862 - val_loss: 0.9569
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9873 - loss: 0.0353 - val_accuracy: 0.7778 - val_loss: 0.6515
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9925 - loss: 0.0387 - val_accuracy: 0.7421 - val_loss: 0.9098
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9898 - loss: 0.0237 - val_accuracy: 0.7673 - val_loss: 0.8267
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9965 - loss: 0.0147 - val_accuracy: 0.7610 - val_loss: 1.0279
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9981 - loss: 0.0081 - val_accuracy: 0.7589 - val_loss: 0.9360
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9998 - loss: 0.0089 - val_accuracy: 0.7505 - val_loss: 1.0756
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9971 - loss: 0.0076 - val_accuracy: 0.7526 - v

In [ ]:
y_pred_proba = model.predict(X_test)
y_pred = (y_pred_proba > 0.5).astype("int32")

print(y_pred[:10])


15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]]


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)



array([[300,  61],
       [ 64,  52]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
0.907705053852527

0.907705053852527